---

- hosts: all
  become: true
  tasks:
  - name: install apache2, support php and update packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

